DECLARE @TableName varchar(100) = '${tableName}', 
@ColumnStatement nvarchar(MAX) = NULL

SELECT @ColumnStatement = COALESCE(@ColumnStatement + N', ',  N'') + NCHAR(13) + NCHAR(10) + N'    ' + [COLUMN_NAME]
    + N' ' + DATA_TYPE
    + CASE
        WHEN CHARACTER_MAXIMUM_LENGTH IS NULL THEN N''
        WHEN CHARACTER_MAXIMUM_LENGTH = -1 THEN N' (MAX)'
        ELSE N'(' + CASE WHEN CHARINDEX('CHAR', DATA_TYPE) > 0 THEN CAST(CHARACTER_MAXIMUM_LENGTH AS NVARCHAR) ELSE CAST(NUMERIC_PRECISION AS NVARCHAR) + N',' + CAST(DATETIME_PRECISION AS NVARCHAR) END + N')'
    END
    + CASE WHEN IS_NULLABLE = N'NO' THEN N' NOT NULL' ELSE N' NULL' END
/*    + CASE
        WHEN COLUMN_DEFAULT IS NULL THEN ''
        ELSE N'  DEFAULT ' + CAST(COLUMN_DEFAULT AS NVARCHAR)
    END*/
    FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = @TableName ORDER BY ORDINAL_POSITION;

SELECT 'CREATE TABLE [' + @TableName + '] (' + @ColumnStatement + ')' AS [Query];

